### ISSUE TITLE
Citadel Services

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/eos-old#11]
Citadel services don't exist.

Currently none exist that would impact fitting stats, but we might want to include them for two reasons.
1. In case CCP did add one that affected fitting stats.
2. We could calculate fuel usage

CCP will be adding other structures (that will likely have service slots), so this could be used for more than just these.

Perhaps:
`fit.modules.service.equip(ModuleService(2048, state=State.online))`

**Comment by DarkFenX** [comment]
Gonna transfer just ticket with a broader scope - "Structures Not Supported by Eos". Closing this one.
