### ISSUE TITLE
Add Validation Check - Ships/Modules vs Structures/Structure Modules

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/eos-old#20]
So I implemented Structures in #17 which works beautifully, but there is one validation we actually _do_ have the data to do.

Specifically, take this block of code: (borrowed from `holder_class.py`)

```
    ModuleHigh: lambda item: (
        (
            item.category == Category.module or
            item.category == Category.structureModule
         ) and
        Slot.module_high in item.slots
    ),
    ModuleMed: lambda item: (
        (
            item.category == Category.module or
            item.category == Category.structureModule
         ) and
        Slot.module_med in item.slots
    ),
    ModuleLow: lambda item: (
        (
            item.category == Category.module or
            item.category == Category.structureModule
         ) and
        Slot.module_low in item.slots
    ),
    Rig: lambda item: (
        (
            item.category == Category.module or
            item.category == Category.structureModule
        ) and
        Slot.rig in item.slots
    ),
    Ship: lambda item: (
        item.category == Category.ship or
        item.category == Category.structure
    ),
```

Because structures were literally implemented _as_ ships, this makes it easy to apply all the same current validations for them that we do for ships (since structure modules belong in the same locations, etc, this makes sense).

The down side is that there's nothing to prevent cross contamination of them.  You are allowed to fit a structure module on a ship, and a regular module on a structure.

Since we have the category data for these, it should be fairly simple to add in a validation that checks to make sure that the category of the ship matches the category of the module.  If it fails, throw an exception.

**Comment by DarkFenX** [comment]
I suggest to postpone this question to a later date. We already discussed structures are not the same as ships in some regards. It needs additional investigation until any decisions are made.
