### ISSUE TITLE
Skills Require Sub-requirements Incorrectly

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/eos-old#24]
Simple example.  Take a Rig (which has other issues with skills, but that's another issue, literally).

Basic rigs skill requirement looks something like this:

```
Jury Rigging I
       Mechanics III
```

In order to train Jury Rigging I, you need to have Mechanics III.

But what if a character _did_ have Jury Rigging I and somehow never trained Mechanics III?  Okay, this isn't possible for rigs but it _is_ possible for a number of ships/modules that CCP has reworked, the most prominent being Command Ships.  There are _many_ pilots who can fly a command ship, but cannot run links (soon to be bursts), and links are a prerequisite to command ships.

For those pilots, Eos will currently throw an exception, when it's actually a completely legal fit.

Take this code:

```
from eos import *
from eos.holder_filter import *

data_handler = JsonDataHandler('C:\Temp\PhobosJSONDump\TQ')  # Folder with Phobos data dump
cache_handler = JsonCacheHandler('C:\Temp\PhobosJSONDump\EosCache\eos_tq.json.bz2')
SourceManager.add('tiamat', data_handler, cache_handler, make_default=True)

fit = Fit()

#fit.skills.add(Skill(26252, level=1)) # Jury Rigging I
#fit.skills.add(Skill(3392, level=3)) # Mechanics III

fit.ship = Ship(40340)  # Upwell Palantine Keepstar
fit.rigs.equip(Rig(37275))  # Standup XL-Set Extinction Level Weapons Suite II

fit.validate()
pass
```

As it stands, this code will throw an exception that you're missing skill 26252, as it should.

Uncomment the line with 26252.  Eos will throw an exception that you are missing skill 3392.  _Which it should not_.

Uncomment both lines and Eos is happy.

This should be a fairly straight forward (hopefully) change to make the validation not recursive on ships/modules/rigs/etc.

**Comment by DarkFenX** [comment]
Eos will throw exception just for skills not meeting prereqs. It will not show ship there, as far as i understand. If you wish you can ignore skill's skill requirement errors after receiving exception.

Considering there's possibility to do this, i think it's not rational to change API to allow fine-tuning for this edge case.

**Comment by DarkFenX** [comment]
> Uncomment the line with 26252. Eos will throw an exception that you are missing skill 3392. Which it should not.

Consider all the info eos provides to you. Besides telling which skills are missing, it shows you which holder is erroneous.

When module is missing its immediate skill requirement, error for that module will be thrown with missing skill. However, when immediate requirement of module is satisfied but skill is missing another skill requirement, error will be thrown *for that skill* which has requirement missing. If you wish to support such edge-cases, simply ignore any skill requirement errors for Skill holders.

**Comment by Ebag333** [comment]
>When module is missing its immediate skill requirement, error for that module will be thrown with missing skill. However, when immediate requirement of module is satisfied but skill is missing another skill requirement, error will be thrown for that skill which has requirement missing. If you wish to support such edge-cases, simply ignore any skill requirement errors for Skill holders.

I understand what you're getting at, and you have a valid point.

The problem is that this isn't an edge case.  The standard case is to not require the sub-reqs, there are no edge cases where they are required (there's an edge case for rigs where skill reqs aren't required at all).

Okay, so we have two things going on here.

1) Fitting validity - prereqs aren't required, and shouldn't cause fits to fail.
2) Character with missing prereqs - Should be notified prereqs are missing.

Um.  2 seems to be handled more efficiently on the UI side, I'm not sure that a `fitting engine` cares whether a character has a particular set of skills that don't apply at all to the fit it's calculating.

It'd certainly be _nice_ to pass back a warning, but I don't think that this should be passed back as an exception.

**Comment by DarkFenX** [comment]
Use new repo from now on.
